import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  pressedFeedback: { transform: [{ scale: 0.96 }], opacity: 0.8 },
  safeArea: { flex: 1, backgroundColor: colors.bg },
  loadingScreen: { flex: 1, backgroundColor: colors.bg, alignItems: 'center', justifyContent: 'center' },
  scrollContent: { padding: 16, paddingBottom: 40, gap: 14 },

  pageTitle: { fontSize: 20, fontWeight: '700', color: colors.goldBright, marginBottom: 2 },
  pageSub: { fontSize: 13.5, color: colors.muted, marginBottom: 4 },

  heroCoins: { backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.gold, borderRadius: 14, padding: 16, alignItems: 'center' },
  heroLabel: { fontSize: 10.5, letterSpacing: 1, color: colors.muted },
  heroValue: { fontSize: 30, fontWeight: '700', color: colors.goldBright, marginTop: 4 },
  heroUnit: { fontSize: 14, color: colors.muted, fontWeight: '500' },

  card: { backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 12, padding: 16 },
  cardTitle: { fontSize: 11, letterSpacing: 0.8, color: colors.goldBright, marginBottom: 4, fontWeight: '700' },
  cardHint: { fontSize: 12, color: colors.muted, marginBottom: 10, lineHeight: 17 },

  subsectionTitle: { marginTop: 14, paddingTop: 12, borderTopWidth: 1, borderTopColor: colors.borderSoft, borderStyle: 'dashed' },
  subsectionTitleText: { fontSize: 10, letterSpacing: 0.8, color: colors.muted },

  fieldRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.borderSoft },
  fieldLabel: { fontSize: 14, color: colors.parchment, flexShrink: 1 },
  fieldControl: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  fieldInput: { width: 70, height: 40, backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 7, color: colors.parchment, fontSize: 15, textAlign: 'center', paddingVertical: 0 },
  fieldUnit: { fontSize: 12, color: colors.muted },

  sexToggle: { flexDirection: 'row', gap: 6 },
  sexChip: { minHeight: 38, paddingHorizontal: 14, borderRadius: 7, borderWidth: 1, borderColor: colors.borderSoft, backgroundColor: colors.panel2, alignItems: 'center', justifyContent: 'center' },
  sexChipSelected: { backgroundColor: colors.gold, borderColor: colors.gold },
  sexChipText: { fontSize: 13, color: colors.muted },
  sexChipTextSelected: { color: colors.bg, fontWeight: '700' },

  weightDisplay: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  weightVal: { fontSize: 15, color: colors.goldBright, fontWeight: '700' },
  updateLink: { fontSize: 12, color: colors.muted, textDecorationLine: 'underline' },

  activityOpt: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 11, minHeight: 44, borderRadius: 9, borderWidth: 1, borderColor: colors.borderSoft, backgroundColor: colors.panel2 },
  activityOptSelected: { borderColor: colors.gold },
  activityRadio: { width: 16, height: 16, borderRadius: 8, borderWidth: 2, borderColor: colors.borderSoft, alignItems: 'center', justifyContent: 'center' },
  activityRadioSelected: { borderColor: colors.gold },
  activityRadioDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.gold },
  activityName: { fontSize: 14, color: colors.parchment },
  activityDesc: { fontSize: 11.5, color: colors.muted, marginTop: 1 },

  toggleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  switchTrack: { width: 42, height: 24, borderRadius: 12, backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.borderSoft, justifyContent: 'center' },
  switchTrackOn: { backgroundColor: colors.availableGreen, borderColor: colors.availableGreen },
  switchKnob: { width: 18, height: 18, borderRadius: 9, backgroundColor: colors.parchment, marginLeft: 2 },
  switchKnobOn: { marginLeft: 22 },

  customTdeeWrap: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 12 },
  customTdeeInput: { width: 100, height: 42, backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.gold, borderRadius: 8, color: colors.parchment, fontSize: 17, textAlign: 'center' },

  calcChain: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 16, paddingTop: 14, borderTopWidth: 1, borderTopColor: colors.borderSoft, borderStyle: 'dashed' },
  calcItem: { alignItems: 'center', flexShrink: 1 },
  calcLabel: { fontSize: 9.5, letterSpacing: 0.3, color: colors.muted },
  calcValue: { fontSize: 17, fontWeight: '700', color: colors.goldBright, marginTop: 5 },
  calcValueSmall: { fontSize: 15, fontWeight: '700', color: colors.parchment, minWidth: 40, textAlign: 'center' },
  calcValueGreen: { color: colors.availableGreen },
  calcArrow: { color: colors.muted, fontSize: 15, paddingHorizontal: 2 },
  miniStepper: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 5 },
  miniBtn: { width: 26, height: 26, borderRadius: 13, borderWidth: 1, borderColor: colors.gold, backgroundColor: colors.panel2, alignItems: 'center', justifyContent: 'center' },
  miniBtnText: { color: colors.goldBright, fontSize: 14 },
  deficitWarning: { fontSize: 11.5, color: colors.danger, textAlign: 'center', marginTop: 12, lineHeight: 16 },

  goalSummary: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 4, paddingVertical: 10 },
  goalSummaryItem: { alignItems: 'center', flex: 1 },
  goalSummaryLabel: { fontSize: 10, color: colors.muted, letterSpacing: 0.3 },
  goalSummaryValue: { fontSize: 15, color: colors.goldBright, marginTop: 4, fontWeight: '700' },
  goalArrow: { color: colors.muted, fontSize: 14 },

  logoutBtn: { minHeight: 48, borderRadius: 9, borderWidth: 1, borderColor: colors.danger, alignItems: 'center', justifyContent: 'center', marginTop: 6 },
  logoutBtnText: { color: colors.danger, fontSize: 13, letterSpacing: 0.5, textTransform: 'uppercase', fontWeight: '700' },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(8,6,4,0.72)', alignItems: 'center', justifyContent: 'center', padding: 24 },
  modalCard: { width: '100%', maxWidth: 300, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.gold, borderRadius: 14, padding: 20, alignItems: 'center' },
  modalTitle: { fontSize: 15, color: colors.goldBright, marginBottom: 14, fontWeight: '700' },
  weightModalRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  weightModalInput: { width: 110, height: 46, backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 8, color: colors.parchment, fontSize: 20, textAlign: 'center' },
  modalActions: { flexDirection: 'row', gap: 8, marginTop: 18, width: '100%' },
  modalCancelBtn: { flex: 1, minHeight: 42, borderRadius: 8, backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.borderSoft, alignItems: 'center', justifyContent: 'center' },
  modalCancelBtnText: { color: colors.muted, fontSize: 12 },
  modalConfirmBtn: { flex: 1, minHeight: 42, borderRadius: 8, backgroundColor: colors.gold, alignItems: 'center', justifyContent: 'center' },
  modalConfirmBtnText: { color: colors.bg, fontWeight: '700', fontSize: 12 },

  saveBtn: { minHeight: 48, borderRadius: 9, backgroundColor: colors.gold, alignItems: 'center', justifyContent: 'center', marginTop: 6 },
  saveBtnText: { color: colors.bg, fontSize: 13, letterSpacing: 0.5, textTransform: 'uppercase', fontWeight: '700' },
  toastWrap: { position: 'absolute', bottom: 80, left: 0, right: 0, alignItems: 'center', zIndex: 50 },
  toast: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.availableGreen,
    borderRadius: 24,
    paddingVertical: 10,
    paddingHorizontal: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 6,
  },
  toastIcon: { color: colors.availableGreen, fontSize: 14, fontWeight: '700' },
  toastText: { color: colors.parchment, fontWeight: '600', fontSize: 13 },
});