import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  pressedFeedback: { transform: [{ scale: 0.94 }], opacity: 0.8 },
  safeArea: { flex: 1, backgroundColor: colors.bg },
  loadingScreen: { flex: 1, backgroundColor: colors.bg, alignItems: 'center', justifyContent: 'center' },
  frame: { flex: 1, padding: 16 },

  pageTitle: { fontSize: 20, fontWeight: '700', color: colors.goldBright, marginBottom: 2 },
  pageSub: { fontSize: 13.5, color: colors.muted, marginBottom: 14 },

  sectionTabs: { flexDirection: 'row', gap: 4, backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 9, padding: 4, marginBottom: 14 },
  sectionTab: { flex: 1, minHeight: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 7 },
  sectionTabActive: { backgroundColor: colors.panel },
  sectionTabText: { fontSize: 12.5, color: colors.muted },
  sectionTabTextActive: { color: colors.goldBright, fontWeight: '700' },

  listContent: { gap: 10, paddingBottom: 90 },
  emptyList: { alignItems: 'center', padding: 36, paddingVertical: 44, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 16 },
  emptyListIcon: { fontSize: 34, marginBottom: 10, opacity: 0.7 },
  emptyListTitle: { color: colors.parchment, fontSize: 15, fontWeight: '700', marginBottom: 6 },
  emptyListText: { color: colors.muted, fontSize: 13, textAlign: 'center', lineHeight: 19, maxWidth: 240 },

  card: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    borderRadius: 14,
    padding: 12,
    minHeight: 44,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 2,
  },
  cardEmojiBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.panel2,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardEmoji: { fontSize: 20 },
  cardName: { fontSize: 15, color: colors.parchment, fontWeight: '600' },
  cardNameBrand: { color: colors.muted, fontWeight: '400', fontStyle: 'italic' },
  cardMeta: { fontSize: 11.5, color: colors.muted, marginTop: 2 },
  kcalPill: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 3,
    backgroundColor: colors.panel2,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    borderRadius: 12,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  kcalPillText: { fontSize: 13, color: colors.goldBright, fontWeight: '700' },
  kcalPillUnit: { fontSize: 9.5, color: colors.muted },
  cardDelete: { width: 26, height: 26, alignItems: 'center', justifyContent: 'center' },
  cardDeleteText: { color: colors.muted, fontSize: 13, opacity: 0.6 },

  fab: {
    position: 'absolute',
    right: 20,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 8,
  },
  fabIcon: { fontSize: 30, color: colors.bg, fontWeight: '300', marginTop: -2 },

  editorSafeArea: { flex: 1, backgroundColor: colors.bg },
  editorContent: { padding: 16, paddingBottom: 30 },
  editorHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 18 },
  editorClose: { width: 34, height: 34, borderRadius: 17, borderWidth: 1, borderColor: colors.borderSoft, backgroundColor: colors.panel2, alignItems: 'center', justifyContent: 'center' },
  editorCloseText: { color: colors.muted, fontSize: 15 },
  editorTitle: { fontSize: 17, color: colors.goldBright, fontWeight: '700' },

  nameInput: { backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 9, color: colors.parchment, fontSize: 16, padding: 12, marginBottom: 20, minHeight: 44 },

  recipeCard: {
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    padding: 14,
    marginBottom: 20,
  },
  pickerCard: {
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    padding: 14,
  },

  fieldGroupLabel: { fontSize: 10, letterSpacing: 0.8, color: colors.muted, marginBottom: 6, marginTop: 4 },
  modeTabs: { flexDirection: 'row', gap: 4, backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 9, padding: 4, marginBottom: 14 },
  modeTab: { flex: 1, minHeight: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 7 },
  modeTabActive: { backgroundColor: colors.panel },
  modeTabText: { fontSize: 11.5, color: colors.muted, textAlign: 'center' },
  modeTabTextActive: { color: colors.goldBright, fontWeight: '700' },

  orderPanel: { backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 8, padding: 14 },
  orderPanelHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  orderPanelTitle: { fontSize: 10, letterSpacing: 0.6, color: colors.muted },
  orderPanelCount: { fontSize: 10, color: colors.muted },
  orderEmptyText: { color: colors.muted, fontStyle: 'italic', fontSize: 13.5, paddingVertical: 6 },
  orderRow: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: colors.borderSoft },
  orderRowName: { flex: 1, color: colors.parchment, fontSize: 13.5 },
  orderRowGrams: { color: colors.muted, fontSize: 11.5, minWidth: 32, textAlign: 'center' },
  orderRowKcal: { color: colors.gold, fontSize: 12 },
  orderRemove: { width: 26, height: 26, alignItems: 'center', justifyContent: 'center' },
  orderRemoveText: { color: colors.danger, fontSize: 14 },
  miniBtn: { width: 30, height: 30, borderRadius: 6, borderWidth: 1, borderColor: colors.borderSoft, backgroundColor: colors.panel, alignItems: 'center', justifyContent: 'center' },
  miniBtnText: { color: colors.goldBright, fontSize: 15 },
  orderSubtotal: { textAlign: 'right', marginTop: 8, fontSize: 12, color: colors.muted },
  orderSubtotalVal: { color: colors.goldBright, fontWeight: '700' },

  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.panel2,
    borderWidth: 1.5,
    borderColor: colors.borderSoft,
    borderRadius: 22,
    marginBottom: 10,
    paddingHorizontal: 14,
  },
  searchBoxFocused: { borderColor: colors.gold, backgroundColor: colors.panel },
  searchIcon: { fontSize: 14, marginRight: 8, opacity: 0.6 },
  searchInput: { flex: 1, minHeight: 46, color: colors.parchment, fontSize: 15 },
  searchClear: { width: 24, height: 24, borderRadius: 12, backgroundColor: colors.borderSoft, alignItems: 'center', justifyContent: 'center', marginLeft: 6 },
  searchClearText: { color: colors.parchment, fontSize: 11 },
  searchResultRow: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 10, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.borderSoft },
  searchResultName: { flex: 1, color: colors.parchment, fontSize: 14 },
  searchResultKcal: { color: colors.muted, fontSize: 11.5 },

  categoryRow: { gap: 8, paddingVertical: 4, marginBottom: 10 },
  categoryChip: { minHeight: 36, paddingHorizontal: 14, borderRadius: 18, borderWidth: 1, borderColor: colors.borderSoft, backgroundColor: colors.panel2, alignItems: 'center', justifyContent: 'center' },
  categoryChipActive: { backgroundColor: colors.gold, borderColor: colors.gold },
  categoryChipText: { color: colors.muted, fontSize: 12.5 },
  categoryChipTextActive: { color: colors.bg, fontWeight: '700' },

  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  item: { width: '47%', backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 8, padding: 12, minHeight: 44 },
  itemEmoji: { fontSize: 20, marginBottom: 4 },
  itemName: { fontSize: 14, color: colors.parchment },
  itemBrand: { fontSize: 11, color: colors.muted, fontStyle: 'italic', marginTop: 1 },
  itemPrice: { fontSize: 12, color: colors.goldBright, marginTop: 6 },

  manualRow: { marginBottom: 16 },
  manualRowNoBorder: {},
  manualLabel: { fontSize: 13, color: colors.muted, marginBottom: 6 },
  manualInput: { backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 9, color: colors.parchment, fontSize: 22, textAlign: 'center', padding: 14 },
  manualHint: { fontSize: 11.5, color: colors.muted, marginTop: 8, lineHeight: 16 },
  toggleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  fieldLabel: { fontSize: 14.5, color: colors.parchment, marginBottom: 3 },
  switchTrack: { width: 42, height: 24, borderRadius: 12, backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.borderSoft, justifyContent: 'center' },
  switchTrackOn: { backgroundColor: colors.availableGreen, borderColor: colors.availableGreen },
  switchKnob: { width: 18, height: 18, borderRadius: 9, backgroundColor: colors.parchment, marginLeft: 2 },
  switchKnobOn: { marginLeft: 22 },
  // ---- Modal de cantidad (mismo patrón que Mercader) ----
  modalOverlay: { flex: 1, backgroundColor: 'rgba(8,6,4,0.75)', alignItems: 'center', justifyContent: 'center', padding: 24 },
  modalCard: { width: '100%', maxWidth: 340, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.gold, borderRadius: 14, padding: 20, alignItems: 'center' },
  quantityPanelName: { fontSize: 17.5, color: colors.goldBright, marginBottom: 10 },
  quantityPanelRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  quantityPanelInput: { width: 80, minHeight: 44, backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 8, paddingHorizontal: 10, color: colors.parchment, fontSize: 17.5 },
  quantityPanelUnit: { color: colors.muted, fontSize: 13, textTransform: 'uppercase' },
  quantityPanelKcal: { marginLeft: 'auto', color: colors.goldBright, fontSize: 16.5, fontWeight: '700' },
  qpAddBtn: { minHeight: 44, marginTop: 12, borderRadius: 8, backgroundColor: colors.gold, alignItems: 'center', justifyContent: 'center', width: '100%' },
  qpAddBtnDisabled: { backgroundColor: colors.border },
  qpAddBtnText: { color: colors.bg, fontWeight: '700', fontSize: 15 },
  modalCancel: { minHeight: 44, alignItems: 'center', justifyContent: 'center', marginTop: 8 },
  modalCancelText: { color: colors.muted, fontSize: 15 },
  exerciseTypeTabs: { flexDirection: 'row', gap: 4, backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 8, padding: 3, marginBottom: 14, width: '100%' },
  exerciseTypeTab: { flex: 1, minHeight: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 6 },
  exerciseTypeTabActive: { backgroundColor: colors.gold },
  exerciseTypeTabText: { fontSize: 12.5, color: colors.muted },
  exerciseTypeTabTextActive: { color: colors.bg, fontWeight: '700' },
  exerciseSourceNote: { textAlign: 'center', fontSize: 10.5, color: colors.muted, fontStyle: 'italic', marginBottom: 8 },

  editorActions: { flexDirection: 'row', gap: 10, padding: 16, borderTopWidth: 1, borderTopColor: colors.borderSoft },
  editorBtnDelete: { flex: 1, minHeight: 46, borderRadius: 9, borderWidth: 1, borderColor: colors.danger, alignItems: 'center', justifyContent: 'center' },
  editorBtnDeleteText: { color: colors.danger, fontSize: 12.5, letterSpacing: 0.5, textTransform: 'uppercase', fontWeight: '700' },
  editorBtnSave: { flex: 2, minHeight: 46, borderRadius: 9, backgroundColor: colors.gold, alignItems: 'center', justifyContent: 'center' },
  editorBtnSaveText: { color: colors.bg, fontSize: 12.5, letterSpacing: 0.5, textTransform: 'uppercase', fontWeight: '700' },
});